// File: /Users/liborballaty/LocalProjects/GitHubProjectsDocuments/fala_madeira/src/content/bundled.ts
// Description: Bundled default content packs — the last rung of the content repository's
//   resolution chain (memory → StorageAdapter cache → network → bundled; see
//   docs/CONTENT-ARCHITECTURE.md §10). Ships inside the app bundle so a fresh install
//   with no network and no cache still has content. Ships the seed Structured
//   Course pack (src/content/packs/seed-course.ts, generated by
//   scripts/seed-content.mjs — the 56 legacy lessons mapped verbatim).
//
//   CONTRACT for adding further bundled packs:
//   1. Generate the seed pack as a module under src/content/packs/, e.g.
//      src/content/packs/seed-course.ts exporting a `const seedCoursePack: ContentPack`
//      (a generated .ts module is preferred over .json — tsconfig.json does not enable
//      resolveJsonModule, and a typed const gets compile-time checking for free).
//      The pack must pass validateContentPack (scripts/validate-content.mjs) and SHOULD
//      carry its publish-time `checksum` (sha256 hex of canonicalPackPayload(pack)).
//   2. Import it here and add it to BUNDLED_PACKS — one import line + one array entry:
//        import { seedCoursePack } from './packs/seed-course';
//        export const BUNDLED_PACKS: ContentPack[] = [seedCoursePack];
//   Nothing else changes: the repository already merges bundled packs (by id) beneath
//   cache/network copies, so a newer published version of the same pack id always wins.
// Author: Libor Ballaty (with assistant)
// Created: 2026-07-09

import { ContentPack } from './schema';
import { seedCoursePack } from './packs/seed-course';

/**
 * Packs compiled into the app bundle. Used only for pack ids not already
 * satisfied by the cache or the network (server copies are authoritative).
 */
export const BUNDLED_PACKS: ContentPack[] = [seedCoursePack];
