// File: /Users/liborballaty/LocalProjects/GitHubProjectsDocuments/fala_madeira/src/features/legal/ai-use.ts
// Description: AI-use disclosure content for FalaMadeira as a typed LegalDocument constant.
//   DRAFT — pending legal review. EU AI Act transparency notice: AI interaction disclosure,
//   synthetic-voice disclosure, what is (and is not) sent to the model, human-review status,
//   and honest limitations per the product's "truthful scope" guardrail.
// Author: Libor Ballaty (with assistant)
// Created: 2026-07-09

import { LegalDocument } from './types';

export const AI_USE_DISCLOSURE: LegalDocument = {
  id: 'ai-use',
  title: 'AI Disclosure',
  version: '0.1.0',
  lastUpdated: '2026-07-09',
  status: 'draft',
  intro: [
    'FalaMadeira uses artificial intelligence at its core. This page explains plainly what the AI does, what data it sees, and where it falls short.',
  ],
  sections: [
    {
      heading: '1. You are interacting with an AI',
      paragraphs: [
        'The tutors in FalaMadeira (such as Maria) are fictional AI characters, not real people. Their replies are generated by Google’s Gemini model. No human is on the other side of the conversation.',
        'This notice is provided in line with the EU AI Act’s transparency requirements.',
      ],
    },
    {
      heading: '2. The voices are synthetic',
      paragraphs: [
        'The audio you hear in lessons and conversations is machine-generated speech (currently Google Gemini text-to-speech; Microsoft Azure voices are planned as an alternative). It is not a recording of a human speaker.',
      ],
    },
    {
      heading: '3. What the AI does',
      bullets: [
        'acts as your conversation partner and tutor, in free chat and lesson-linked practice;',
        'generates lesson content, scenario practice, and translations;',
        'analyzes your answers and mistakes to give feedback and suggestions.',
      ],
    },
    {
      heading: '4. What is sent to the AI',
      paragraphs: [
        'When you use an AI feature, we send to Google’s Gemini API, through our own server:',
      ],
      bullets: [
        'the messages you type, or the text transcribed from your voice input;',
        'relevant context, such as the current lesson topic and your chosen tutor;',
        'for audio playback, the text to be spoken aloud.',
      ],
    },
    {
      heading: '5. What is not sent',
      bullets: [
        'your password or authentication credentials;',
        'your raw voice recordings — speech is converted to text by your browser or device, and only the text reaches the AI;',
        'your data is never sold, and we do not use it for advertising.',
      ],
    },
    {
      heading: '6. Human review',
      paragraphs: [
        'No one at SearchingFool routinely reads your AI conversations. Our team may see specific data if you include it in a support ticket or diagnostic logs you choose to send.',
        'Our AI provider processes conversation content to generate responses under its API data-processing terms. [Provider data-use and training terms to be confirmed in legal review.]',
      ],
    },
    {
      heading: '7. Accuracy and limitations — please read this',
      paragraphs: ['The AI is genuinely useful for practice, but it is not perfect:'],
      bullets: [
        'it can produce incorrect Portuguese, or phrasing that is standard European Portuguese rather than authentically Madeiran;',
        'its explanations of grammar or culture can be wrong or oversimplified;',
        'its feedback on your mistakes is a helpful signal, not an authoritative assessment;',
        'FalaMadeira is not a certification body — it cannot certify your language level, and it is no substitute for human teachers or real immersion.',
      ],
    },
    {
      heading: '8. Your choices',
      bullets: [
        'You consent to AI processing when you sign up; you can withdraw that consent at any time by contacting support@searchingfool.com or deleting your account (AI features require this consent to function).',
        'Voice input is always optional — you can type instead.',
        'You can report AI errors through the in-app correction and support tools; reports are reviewed and used to improve the content.',
      ],
    },
  ],
};
