// File: /Users/liborballaty/LocalProjects/GitHubProjectsDocuments/fala_madeira/src/features/legal/terms.ts
// Description: Terms of Service content for FalaMadeira as a typed LegalDocument constant.
//   DRAFT — pending legal review. Controller: SearchingFool (Czech Republic),
//   contact support@searchingfool.com. Written to be accurate to what the app actually
//   does (free at launch, AI tutoring via Gemini, in-app account deletion).
// Author: Libor Ballaty (with assistant)
// Created: 2026-07-09

import { LegalDocument } from './types';

export const TERMS_OF_SERVICE: LegalDocument = {
  id: 'terms',
  title: 'Terms of Service',
  version: '0.1.0',
  lastUpdated: '2026-07-09',
  status: 'draft',
  intro: [
    'These terms explain what you can expect from FalaMadeira and what we expect from you. We have tried to keep them short and readable.',
  ],
  sections: [
    {
      heading: '1. Who we are',
      paragraphs: [
        'FalaMadeira is operated by SearchingFool, based in the Czech Republic. You can reach us at support@searchingfool.com.',
      ],
    },
    {
      heading: '2. The service',
      paragraphs: [
        'FalaMadeira is a language-learning app for European Portuguese as spoken in Madeira. It offers structured lessons, vocabulary and listening practice, and conversation practice with an AI tutor.',
        'Parts of the service are generated by artificial intelligence. How that works, what data is involved, and its limitations are described in our AI Disclosure, which forms part of these terms.',
      ],
    },
    {
      heading: '3. Your account',
      paragraphs: [
        'You need an account (email and password, or a magic sign-in link) to use the app. Keep your credentials safe — you are responsible for activity on your account.',
        'You must be at least 15 years old to create an account (the age of digital consent in the Czech Republic).',
      ],
    },
    {
      heading: '4. Fair use',
      paragraphs: ['When using FalaMadeira you agree not to:'],
      bullets: [
        'use the AI tutor or other features for anything unlawful, abusive, or harmful;',
        'attempt to extract, scrape, or bulk-download our content or other users’ data;',
        'circumvent usage limits (such as daily voice-message limits) or interfere with the service’s operation;',
        'share your account or misrepresent who you are.',
      ],
    },
    {
      heading: '5. AI-generated content',
      paragraphs: [
        'Tutor conversations, generated lessons, translations, and feedback are produced by an AI model. They can be wrong — including incorrect Portuguese, phrasing that is not authentic to Madeira, or mistaken explanations. FalaMadeira is a learning aid, not a certified teacher, examiner, or translation authority.',
        'If you spot an error, please report it through the in-app correction and support tools. We review reports and improve the content.',
      ],
    },
    {
      heading: '6. Content and ownership',
      paragraphs: [
        'The app, its curriculum, and its design remain ours or our licensors’. We grant you a personal, non-transferable licence to use them for your own learning.',
        'When you submit content to us (for example lesson corrections, suggestions, or support tickets), you allow us to use it to operate and improve the service.',
      ],
    },
    {
      heading: '7. Price',
      paragraphs: [
        'FalaMadeira is currently free. Some features have fair-use limits (for example, a daily number of voice messages). If we introduce paid plans in the future, we will tell you clearly in advance, and nothing will be charged without your explicit agreement.',
      ],
    },
    {
      heading: '8. Availability and changes',
      paragraphs: [
        'We work to keep the service available and improving, but it is provided “as is”. Features may change, be added, or be withdrawn. Where a change significantly affects you, we will give reasonable notice.',
      ],
    },
    {
      heading: '9. Ending your account',
      paragraphs: [
        'You can delete your account and data at any time from Profile → Delete Account & Data. Deletion is immediate and cannot be undone.',
        'We may suspend or close accounts that seriously or repeatedly break these terms. Where reasonable, we will warn you first.',
      ],
    },
    {
      heading: '10. Liability',
      paragraphs: [
        'To the extent permitted by law, we are not liable for indirect damage or for consequences of relying on AI-generated learning content. Nothing in these terms limits liability that cannot be limited under applicable law, and nothing affects your statutory consumer rights in the EU.',
      ],
    },
    {
      heading: '11. Governing law',
      paragraphs: [
        'These terms are governed by Czech law. If you are an EU consumer, you also keep the protection of the mandatory consumer laws of your country of residence. Disputes can be brought before the courts competent under applicable law; EU consumers may also use the European Commission’s Online Dispute Resolution platform.',
      ],
    },
    {
      heading: '12. Changes to these terms',
      paragraphs: [
        'We may update these terms. The version and date at the top always show the current revision. For material changes we will notify you in the app before they take effect.',
      ],
    },
    {
      heading: '13. Contact',
      paragraphs: ['Questions about these terms: support@searchingfool.com.'],
    },
  ],
};
